"""custom_user

Revision ID: 87407974f44c
Revises:
Create Date: 2025-12-23 12:01:22.179465

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87407974f44c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата изменения",
        ),
        sa.Column(
            "username",
            sa.String(length=100),
            nullable=False,
            comment="Пользователь",
        ),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column(
            "first_name", sa.String(length=100), nullable=True, comment="Имя"
        ),
        sa.Column(
            "second_name",
            sa.String(length=100),
            nullable=True,
            comment="Фамилия",
        ),
        sa.Column(
            "last_name",
            sa.String(length=100),
            nullable=True,
            comment="Отчество",
        ),
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            nullable=False,
            comment="Суперпользователь",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Активен"
        ),
        sa.Column(
            "is_staff", sa.Boolean(), nullable=False, comment="Персонал"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="user_email_key_uniq"),
        sa.UniqueConstraint("username", name="user_username_key_uniq"),
    )
    op.create_index(
        op.f("ix_custom_users_email"), "custom_users", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_custom_users_username"),
        "custom_users",
        ["username"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_custom_users_username"), table_name="custom_users")
    op.drop_index(op.f("ix_custom_users_email"), table_name="custom_users")
    op.drop_table("custom_users")
    # ### end Alembic commands ###
